# Generated by Django 5.2.7 on 2025-11-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_userprofile_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
